name: Run all examples

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "user_guide/**"
      - "tutorials/**"
  workflow_dispatch:  # Enables manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  hello_world:
    uses: unionai/unionai-examples/.github/workflows/register_and_run_wf.yml@run-ci
    with:
      workflow_directory: user_guide/core_concepts/actors/serverless
      workflow_file: hello_world.py
      workflow_name: wf
